# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
    tags:
     - "*"
  pull_request:
    branches: [ master ]
   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install required libs
      run: sudo apt install libjinput-java libxcursor-dev libxrandr-dev libxxf86vm-dev
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -Ddo.delete=yes generate-all compile jars release maven
    - uses: actions/upload-artifact@v1
      with:
        name: lwjgl-dist
        path: dist/
    - name: Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/lwjgl-*.zip
        overwrite: true
        file_glob: true